---
-
  name: "docker"
  become: yes
  hosts: worker02
  vars_files:
    - /home/ubuntu/secrets.yml

  roles:
    - docker

  tasks:
    - name: "Launch nginx container"
      docker_container:
        name: webapp
        image: nginx
        ports:
          - "80:80"
