all:
  # vars:
  #   ansible_ssh_private_key_file: /home/ubuntu/chris.pem
  children:
    ansible:
      hosts:
        localhost:
          ansible_connection: local
          ansible_user: ubuntu
    prod:
      vars:
        env: production
        ansible_user: ubuntu
        ansible_password: Chris
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

      hosts:
        worker01:
          ansible_host: 172.31.86.192
          hostname: AnsibleWorker01

        worker02:
          ansible_host: 172.31.88.69
          hostname: AnsibleWorker02
