---
-
  name: "packages installation"
  become: yes
  hosts: worker01

  tasks:
    - name: package install
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - nginx
      when: ansible_distribution == "Ubuntu"
      # or: ansible_facts['os_family'] == "Debian"

    - name: "clean folder"
      file:
        path: /var/www/html
        state: absent
    - name: "create folder"
      file:
        path: /var/www/html
        state: directory
    - name: "create index.html"
      copy:
        content: Christophe TP12
        dest: /var/www/html/index.html

    - name: "nginx enable"
      service:
        name: nginx
        state: started
        enabled: yes

