apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysql
  name: mysql-pod
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: password
    - name: MYSQL_DATABASE
      value: eazytraining
    - name: MYSQL_USER
      value: eazy
    - name: MYSQL_PASSWORD
      value: eazy
    image: mysql
    name: mysql-volume
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: msql-data
  volumes:
  - name: mysql-data
    hostPath:
      path: /data-volume
      type: DirectoryOrCreate
