apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  storageClassName: mysql
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce    # also possible: ReadOnlyMany, ReadWriteMany
  hostPath:
    path: /data-pv
